services:
  - type: web
    name: my-prono-front
    runtime: static
    buildCommand: npm ci && npm run build:prod
    staticPublishPath: dist/my-pronostic-frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
